### ISSUE TITLE
RocketCommanderXNA 4.0

### ISSUE THREAD

**Issue by neau33** [DDReaper/XNAGameStudio#17]
@SimonDarksideJ
Here's RocketCommander migrated to XNA 4.0 in case you would be interested to port it for MonoGame.
[https://xneosite.000webhostapp.com/imppaa/lataukset/download.php?path=RocketCommanderXna.zip](url)

**Comment by SimonDarksideJ** [comment]
Thanks, will check it out and add it to the docs.
Great work @neau33

**Comment by neau33** [comment]
@SimonDarksideJ

Thanks for the message

Here's another one:
I'v been been messing with this old FPS game  awhile  and it makes me almost crazy.
It would be nice if you had time sometimes to take a look at this project and maybe find the points where I do wrong. 

In case you sometimes take a look at this and find some solution so please let me know about how you solved the problem(s).

[https://onedrive.live.com/?authkey=%21Auo4S%5F9v62Y36oE&id=A3ED4F5AFDA0E88%2147299&cid=0A3ED4F5AFDA0E88
](url)
