### ISSUE TITLE
XMLLoadingSample - particles only render in OpenGL and not in DirectX

### ISSUE THREAD

**Issue by DDReaper** [DDReaper/XNAGameStudio#2]
Whilst writing the XMLLoading sample, using the XML Particles XNA sample as a base, I ran in to an issue.
The Shader only currently works for GL platforms and not for DX (e.g. WindowsDX / UWP / Etc)

I suspect it's an issue with the shader somewhere but haven't found the cause yet.

if anyone can help, please dig in and look.

**Comment by WPCrasher** [comment]
Check the order of the items in the input struct to the VS in the .fx ... it needs to directly match the VertexDeclaration used in the game code. :)

**Comment by WPCrasher** [comment]
I may have spoke too soon ... ;-P
See:  http://community.monogame.net/t/solved-xna-3d-particles-sample-port-on-monogame-3-4/6301

It may have to do with the multiple usages (usage indices) for "Position" ...
At the end of the link, you see that they re-arranged the order of the struct elements AS WELL AS the usages of each.

**Comment by DDReaper** [comment]
Thanks for the assist @WPCrasher 
Turned out it was all to do with the vertex formats, seems GL is very forgiving but DX has none of that rubbish :D 
Updated shader and the VertexFormat to match and it's all good now.
